#!/usr/bin/bash

ssh -p2222 root@localhost mkdir -p /root/.ssh
scp -P2222 /home/micke/.ssh/id_rsa.pub root@localhost:/root/.ssh/authorized_keys

# ssh -p2222 root@localhost apk update
# ssh -p2222 root@localhost apk add sshfs
# ssh -p2222 root@localhost modprobe fuse
# ssh -p2222 root@localhost mkdir -p /mnt/apks
# ssh -p2222 root@localhost sshfs micke@192.168.144.79:/home/micke/Repo.lab/moonflower/apks /mnt/apks

scp -P2222 abuild/li.mikael@gmail.com-62df97f2.rsa.pub root@localhost:/etc/apk/keys
ssh -p2222 root@localhost 'echo "http://192.168.1.20/apks/" >> /etc/apk/repositories'
ssh -p2222 root@localhost apk update

scp -P2222 scripts/setup-moonflower root@localhost:/sbin/
ssh -p2222 root@localhost setup-moonflower
