#!/usr/bin/bash

VBoxManage controlvm installerdebug poweroff
sleep 1
VBoxManage modifyvm installerdebug --hda none
sleep 1
VBoxManage unregistervm installerdebug --delete
sleep 1

VBoxManage createvm --name installerdebug --ostype Linux_64 --register --basefolder `pwd`/vm

VBoxManage modifyvm installerdebug --ioapic on
VBoxManage modifyvm installerdebug --memory 3000 --vram 128
VBoxManage modifyvm installerdebug --nic1 nat
VBoxManage modifyvm installerdebug --natpf1 "guestssh,tcp,,2222,,22"

#VBoxManage modifyvm installerdebug --bridgeadapter1 wlp1s0
#VBoxManage modifyvm installerdebug --macaddress1 08002795263C

VBoxManage createhd --filename `pwd`/vm/installerdebug/installerdebug_DISK.vdi --size 80000 --format VDI
VBoxManage storagectl installerdebug --name "SATA Controller" --add sata --controller IntelAhci
VBoxManage storageattach installerdebug --storagectl "SATA Controller" --port 0 --device 0 --type hdd --medium  `pwd`/vm/installerdebug/installerdebug_DISK.vdi
VBoxManage storagectl installerdebug --name "IDE Controller" --add ide --controller PIIX4
VBoxManage storageattach installerdebug --storagectl "IDE Controller" --port 1 --device 0 --type dvddrive --medium `pwd`/iso/alpine-installerdebug-latest-x86_64.iso
VBoxManage modifyvm installerdebug --boot1 dvd --boot2 disk --boot3 none --boot4 none

VBoxManage sharedfolder add installerdebug --name moonflower --hostpath /home/micke/Repo.lab/moonflower
VBoxManage sharedfolder add installerdebug --name micke --hostpath /home/micke/

VBoxManage startvm installerdebug

echo "Waiting for machine to come online"
until ssh -oUserKnownHostsFile=/dev/null -oStrictHostKeyChecking=no -p2222 root@localhost echo "hello"
do
	echo "Waiting..."
	sleep 1
done
